global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "hello-svc"
    scrape_interval: "5s"
    static_configs:
      - targets: ['hello-1:8080']
  - job_name: "formatter-svc"
    scrape_interval: "5s"
    static_configs:
      - targets: ['formatter-1:8082']
